#ifndef ZCE_LIB_CONFIG_H_
#define ZCE_LIB_CONFIG_H_

#define ZCE_USE_LOGMSG 0
#define ZCE_USE_RAPIDXML 0
#define ZCE_USE_LUA 0
#define ZCE_USE_PROTOBUF 1
#define ZCE_USE_SQLITE 1
#define ZCE_USE_MYSQL 0

#endif //ZCE_LIB_CONFIG_H_

